logging:
  pattern:
    console: log@%clr(%d{mm:ss SSS}){blue}%clr(-%5p){red} [%logger] %clr(%m){magenta}%n
  level:
    com.lan: debug
    org.springframework: WARN
    org.hibernate: WARN
# request.header中的token的名称
lan:
  ichat:
    token-name: token
# spring 配置
spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
      enabled: true
  profiles:
    active: win

mybatis:
  mapper-locations: classpath:com/lan/**/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true

# tomcat port
server:
  port: 8087







