logging:
  pattern:
    console: log@%clr(%d{mm:ss SSS}){blue}%clr(-%5p){red} [%logger] %clr(%m){magenta}%n
  level:
    com.lan: debug
    org.springframework: WARN
    org.hibernate: WARN
# request.header中的token的名称
lan:
  ichat:
    token-name: token
# spring 配置
spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
      enabled: true
  profiles:
    active: dev
  redis:
    host: 192.168.0.200
    port: 6379
    pool:
      max-active: 20
      max-idle: 20
      max-wait: 60000
      min-idle: 1
    database: 0
    timeout: 10000
    password:


mybatis:
  mapper-locations: classpath:com/lan/**/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true

# tomcat port
server:
  port: 8087







