// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessage.proto

package org.spoom.im.sdk.server.model.proto;

public final class ChatMessageProto {
  private ChatMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.spoom.im.sdk.server.model.proto.ChatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string msgId = 1;</code>
     */
    String getMsgId();
    /**
     * <code>string msgId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <pre>
     * 标记消息类型，如：群聊信息、点对点消息
     * </pre>
     *
     * <code>int32 chatType = 2;</code>
     */
    int getChatType();

    /**
     * <code>int32 msgType = 3;</code>
     */
    int getMsgType();

    /**
     * <code>string msgFrom = 4;</code>
     */
    String getMsgFrom();
    /**
     * <code>string msgFrom = 4;</code>
     */
    com.google.protobuf.ByteString
        getMsgFromBytes();

    /**
     * <code>string msgTo = 5;</code>
     */
    String getMsgTo();
    /**
     * <code>string msgTo = 5;</code>
     */
    com.google.protobuf.ByteString
        getMsgToBytes();

    /**
     * <code>string body = 6;</code>
     */
    String getBody();
    /**
     * <code>string body = 6;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>string extra = 7;</code>
     */
    String getExtra();
    /**
     * <code>string extra = 7;</code>
     */
    com.google.protobuf.ByteString
        getExtraBytes();

    /**
     * <code>int64 time = 9;</code>
     */
    long getTime();
  }
  /**
   * Protobuf type {@code org.spoom.im.sdk.server.model.proto.ChatMessage}
   */
  public  static final class ChatMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.spoom.im.sdk.server.model.proto.ChatMessage)
      ChatMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatMessage.newBuilder() to construct.
    private ChatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMessage() {
      msgId_ = "";
      chatType_ = 0;
      msgType_ = 0;
      msgFrom_ = "";
      msgTo_ = "";
      body_ = "";
      extra_ = "";
      time_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              msgId_ = s;
              break;
            }
            case 16: {

              chatType_ = input.readInt32();
              break;
            }
            case 24: {

              msgType_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              msgFrom_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              msgTo_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              extra_ = s;
              break;
            }
            case 72: {

              time_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChatMessageProto.internal_static_org_spoom_im_sdk_server_model_proto_ChatMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChatMessageProto.internal_static_org_spoom_im_sdk_server_model_proto_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatMessage.class, Builder.class);
    }

    public static final int MSGID_FIELD_NUMBER = 1;
    private volatile Object msgId_;
    /**
     * <code>string msgId = 1;</code>
     */
    public String getMsgId() {
      Object ref = msgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      }
    }
    /**
     * <code>string msgId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHATTYPE_FIELD_NUMBER = 2;
    private int chatType_;
    /**
     * <pre>
     * 标记消息类型，如：群聊信息、点对点消息
     * </pre>
     *
     * <code>int32 chatType = 2;</code>
     */
    public int getChatType() {
      return chatType_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 3;
    private int msgType_;
    /**
     * <code>int32 msgType = 3;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int MSGFROM_FIELD_NUMBER = 4;
    private volatile Object msgFrom_;
    /**
     * <code>string msgFrom = 4;</code>
     */
    public String getMsgFrom() {
      Object ref = msgFrom_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgFrom_ = s;
        return s;
      }
    }
    /**
     * <code>string msgFrom = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMsgFromBytes() {
      Object ref = msgFrom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTO_FIELD_NUMBER = 5;
    private volatile Object msgTo_;
    /**
     * <code>string msgTo = 5;</code>
     */
    public String getMsgTo() {
      Object ref = msgTo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgTo_ = s;
        return s;
      }
    }
    /**
     * <code>string msgTo = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMsgToBytes() {
      Object ref = msgTo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 6;
    private volatile Object body_;
    /**
     * <code>string body = 6;</code>
     */
    public String getBody() {
      Object ref = body_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRA_FIELD_NUMBER = 7;
    private volatile Object extra_;
    /**
     * <code>string extra = 7;</code>
     */
    public String getExtra() {
      Object ref = extra_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      }
    }
    /**
     * <code>string extra = 7;</code>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      Object ref = extra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 9;
    private long time_;
    /**
     * <code>int64 time = 9;</code>
     */
    public long getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgId_);
      }
      if (chatType_ != 0) {
        output.writeInt32(2, chatType_);
      }
      if (msgType_ != 0) {
        output.writeInt32(3, msgType_);
      }
      if (!getMsgFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msgFrom_);
      }
      if (!getMsgToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, msgTo_);
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, body_);
      }
      if (!getExtraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, extra_);
      }
      if (time_ != 0L) {
        output.writeInt64(9, time_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgId_);
      }
      if (chatType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, chatType_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, msgType_);
      }
      if (!getMsgFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msgFrom_);
      }
      if (!getMsgToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, msgTo_);
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, body_);
      }
      if (!getExtraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, extra_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChatMessage)) {
        return super.equals(obj);
      }
      ChatMessage other = (ChatMessage) obj;

      boolean result = true;
      result = result && getMsgId()
          .equals(other.getMsgId());
      result = result && (getChatType()
          == other.getChatType());
      result = result && (getMsgType()
          == other.getMsgType());
      result = result && getMsgFrom()
          .equals(other.getMsgFrom());
      result = result && getMsgTo()
          .equals(other.getMsgTo());
      result = result && getBody()
          .equals(other.getBody());
      result = result && getExtra()
          .equals(other.getExtra());
      result = result && (getTime()
          == other.getTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId().hashCode();
      hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getChatType();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + MSGFROM_FIELD_NUMBER;
      hash = (53 * hash) + getMsgFrom().hashCode();
      hash = (37 * hash) + MSGTO_FIELD_NUMBER;
      hash = (53 * hash) + getMsgTo().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtra().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChatMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.spoom.im.sdk.server.model.proto.ChatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.spoom.im.sdk.server.model.proto.ChatMessage)
        ChatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChatMessageProto.internal_static_org_spoom_im_sdk_server_model_proto_ChatMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChatMessageProto.internal_static_org_spoom_im_sdk_server_model_proto_ChatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChatMessage.class, Builder.class);
      }

      // Construct using org.spoom.im.sdk.server.model.proto.ChatMessageProto.ChatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgId_ = "";

        chatType_ = 0;

        msgType_ = 0;

        msgFrom_ = "";

        msgTo_ = "";

        body_ = "";

        extra_ = "";

        time_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChatMessageProto.internal_static_org_spoom_im_sdk_server_model_proto_ChatMessage_descriptor;
      }

      public ChatMessage getDefaultInstanceForType() {
        return ChatMessage.getDefaultInstance();
      }

      public ChatMessage build() {
        ChatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ChatMessage buildPartial() {
        ChatMessage result = new ChatMessage(this);
        result.msgId_ = msgId_;
        result.chatType_ = chatType_;
        result.msgType_ = msgType_;
        result.msgFrom_ = msgFrom_;
        result.msgTo_ = msgTo_;
        result.body_ = body_;
        result.extra_ = extra_;
        result.time_ = time_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChatMessage) {
          return mergeFrom((ChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChatMessage other) {
        if (other == ChatMessage.getDefaultInstance()) return this;
        if (!other.getMsgId().isEmpty()) {
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.getChatType() != 0) {
          setChatType(other.getChatType());
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (!other.getMsgFrom().isEmpty()) {
          msgFrom_ = other.msgFrom_;
          onChanged();
        }
        if (!other.getMsgTo().isEmpty()) {
          msgTo_ = other.msgTo_;
          onChanged();
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        if (!other.getExtra().isEmpty()) {
          extra_ = other.extra_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ChatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ChatMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object msgId_ = "";
      /**
       * <code>string msgId = 1;</code>
       */
      public String getMsgId() {
        Object ref = msgId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string msgId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgId = 1;</code>
       */
      public Builder setMsgId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgId = 1;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>string msgId = 1;</code>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgId_ = value;
        onChanged();
        return this;
      }

      private int chatType_ ;
      /**
       * <pre>
       * 标记消息类型，如：群聊信息、点对点消息
       * </pre>
       *
       * <code>int32 chatType = 2;</code>
       */
      public int getChatType() {
        return chatType_;
      }
      /**
       * <pre>
       * 标记消息类型，如：群聊信息、点对点消息
       * </pre>
       *
       * <code>int32 chatType = 2;</code>
       */
      public Builder setChatType(int value) {
        
        chatType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 标记消息类型，如：群聊信息、点对点消息
       * </pre>
       *
       * <code>int32 chatType = 2;</code>
       */
      public Builder clearChatType() {
        
        chatType_ = 0;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <code>int32 msgType = 3;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>int32 msgType = 3;</code>
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 msgType = 3;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private Object msgFrom_ = "";
      /**
       * <code>string msgFrom = 4;</code>
       */
      public String getMsgFrom() {
        Object ref = msgFrom_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgFrom_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string msgFrom = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMsgFromBytes() {
        Object ref = msgFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgFrom = 4;</code>
       */
      public Builder setMsgFrom(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgFrom = 4;</code>
       */
      public Builder clearMsgFrom() {
        
        msgFrom_ = getDefaultInstance().getMsgFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string msgFrom = 4;</code>
       */
      public Builder setMsgFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgFrom_ = value;
        onChanged();
        return this;
      }

      private Object msgTo_ = "";
      /**
       * <code>string msgTo = 5;</code>
       */
      public String getMsgTo() {
        Object ref = msgTo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgTo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string msgTo = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMsgToBytes() {
        Object ref = msgTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgTo = 5;</code>
       */
      public Builder setMsgTo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgTo = 5;</code>
       */
      public Builder clearMsgTo() {
        
        msgTo_ = getDefaultInstance().getMsgTo();
        onChanged();
        return this;
      }
      /**
       * <code>string msgTo = 5;</code>
       */
      public Builder setMsgToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgTo_ = value;
        onChanged();
        return this;
      }

      private Object body_ = "";
      /**
       * <code>string body = 6;</code>
       */
      public String getBody() {
        Object ref = body_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string body = 6;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 6;</code>
       */
      public Builder setBody(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 6;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 6;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }

      private Object extra_ = "";
      /**
       * <code>string extra = 7;</code>
       */
      public String getExtra() {
        Object ref = extra_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          extra_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string extra = 7;</code>
       */
      public com.google.protobuf.ByteString
          getExtraBytes() {
        Object ref = extra_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          extra_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string extra = 7;</code>
       */
      public Builder setExtra(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 7;</code>
       */
      public Builder clearExtra() {
        
        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 7;</code>
       */
      public Builder setExtraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extra_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>int64 time = 9;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>int64 time = 9;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time = 9;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.spoom.im.sdk.server.model.proto.ChatMessage)
    }

    // @@protoc_insertion_point(class_scope:org.spoom.im.sdk.server.model.proto.ChatMessage)
    private static final ChatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChatMessage();
    }

    public static ChatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMessage>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
      public ChatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ChatMessage> getParserForType() {
      return PARSER;
    }

    public ChatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_spoom_im_sdk_server_model_proto_ChatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_spoom_im_sdk_server_model_proto_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021ChatMessage.proto\022#org.spoom.im.sdk.se" +
      "rver.model.proto\"\212\001\n\013ChatMessage\022\r\n\005msgI" +
      "d\030\001 \001(\t\022\020\n\010chatType\030\002 \001(\005\022\017\n\007msgType\030\003 \001" +
      "(\005\022\017\n\007msgFrom\030\004 \001(\t\022\r\n\005msgTo\030\005 \001(\t\022\014\n\004bo" +
      "dy\030\006 \001(\t\022\r\n\005extra\030\007 \001(\t\022\014\n\004time\030\t \001(\003B\022B" +
      "\020ChatMessageProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_spoom_im_sdk_server_model_proto_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_spoom_im_sdk_server_model_proto_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_spoom_im_sdk_server_model_proto_ChatMessage_descriptor,
        new String[] { "MsgId", "ChatType", "MsgType", "MsgFrom", "MsgTo", "Body", "Extra", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
