package com.lan.ichat;

import com.lan.ichat.dao.UserMapper;
import com.lan.ichat.model.UserEntity;
import com.lan.ichat.service.AdminService;
import com.lan.ichat.service.UserService;
import org.apache.commons.codec.digest.DigestUtils;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import java.util.Date;
import java.util.Random;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest
public class IchatApplicationTests {
    private final static Logger logger = LoggerFactory.getLogger(IchatApplicationTests.class);
    @Autowired
    private UserService userService;
    @Autowired
    private UserMapper userMapper;

    @Test
    public void contextLoads() {
    }
//
//    @Test
//    public void testInsertUsers() {
//        String[] a = new String[]{
//                "丹尼尔修士",
//                "治安官玛克布莱德",
//                "恐怖骸骨",
//                "骷髅法师",
//                "治安官杜汉",
//                "雷米",
//                "黑衣威利",
//                "书记员达尔塔",
//                "议员米尔斯迪普",
//                "拜瑞巴克大使",
//                "厨师格鲁奥",
//                "旅店老板斯密茨",
//                "酒吧老板汉恩",
//                "基特斯",
//                "亚伯克隆比",
//                "治安官哈迦德",
//                "旅店老板法雷",
//                "管理员弗索姆",
//                "札克乌尔",
//                "盲眼玛丽",
//                "塞欧克瑞图斯",
//                "伊莉莎",
//                "加塞尔佐格",
//                "森格",
//                "厨师布雷纳",
//                "所罗门镇长",
//                "贝利格拉布",
//                "酒吧老板丹尼尔",
//                "格里兹尔",
//                "基沙恩下士",
//                "女牧师安妮塔",
//                "高阶牧师劳瑞娜",
//                "女牧师洁塞塔",
//                "达希",
//                "码头管理员巴伦",
//                "老瞎眼",
//                "葛瑞森船长",
//                "霍格",
//                "乌尔图斯",
//                "酒吧老板杜宾斯",
//                "城镇公告员",
//                "多伦上尉",
//                "黑石前锋",
//                "萨瑞尔祖恩",
//                "军需官刘易斯",
//                "玛拉索姆公爵",
//                "利爪队长",
//                "芬罗斯",
//                "铁匠阿古斯",
//                "犹勒",
//                "斯拉克",
//                "布拉克",
//                "鲁伯斯",
//                "摩拉迪姆",
//                "索尔",
//                "骸骨魔",
//                "奈法鲁",
//                "纳雷塞特",
//                "莱普利瑟斯",
//                "死神4000型",
//                "纳拉克西斯",
//                "暗皮刺客",
//                "瘟疫食尸鬼",
//                "查特",
//                "哥布林木匠",
//                "斯尼德",
//                "拉克佐",
//                "曲奇",
//                "重拳先生",
//                "绿皮队长",
//                "血顶巫医",
//                "卡洛尔",
//                "劈颅巫医",
//                "范高雷中尉",
//                "小霜鬃巨魔",
//                "艾尔加丁爵士",
//                "巴尔瑟拉",
//                "辛达尔",
//                "泰希斯",
//                "尤瓦中士",
//                "布鲁斯下士",
//                "科博克",
//                "尼麦兹修士",
//                "纠缠恐兽",
//                "卡雷布下士",
//                "指挥官菲斯托姆",
//                "克拉兹克",
//                "劈颅秘法师",
//                "劈颅兽王",
//                "骷髅看守",
//                "骷髅医师",
//                "玛特",
//                "乔舒",
//                "布林",
//                "所罗门",
//                "凯文",
//                "凯雷",
//                "艾瑞克",
//                "吉恩",
//                "丹纳",
//                "卡梅伦",
//                "约翰",
//                "丽莎",
//                "亚伦",
//                "乔斯",
//                "玛尔苏斯中士",
//                "书呆子赫罗德",
//                "麦佐斯",
//                "丹努文队长",
//                "小森林熊",
//                "维里副队长",
//                "尘魔",
//                "山狗首领",
//                "山狗",
//                "南森",
//                "麦迪逊",
//                "瑞吉儿",
//                "伊伦",
//                "汉娜",
//                "斯通纳德制图师",
//                "斯通纳德萨满祭司",
//                "盐鳞首领",
//                "盐鳞强盗",
//                "拉尔斯",
//                "萨缪尔修士",
//                "威尔海姆修士",
//                "帕克斯顿修士",
//                "尼尔斯修士",
//                "瑞尼尔副队长",
//                "格瑞穆纳尔",
//                "哈塔什",
//                "索尔塔什",
//                "苏塔佐尔",
//                "萨罗斯",
//                "哈洛姆",
//                "欧格鲁姆",
//                "卡托什",
//                "巴纳拉什",
//                "藓皮秘法师",
//                "藓皮突击队员",
//                "蓝腮强盗",
//                "沼泽之王",
//                "黑铁爆破手",
//                "甘祖拉恩",
//                "河爪萨满祭司",
//                "高恩",
//                "菲尔顿副队长",
//                "勘察员维尔加",
//                "盐齿钳嘴鳄",
//                "拉格弗斯上尉",
//                "艾尔丁",
//                "迷雾谷猩猩",
//                "丛林大猩猩",
//                "霜鬃巨魔",
//                "霜鬃暗法师",
//                "小黑熊",
//                "黑熊",
//                "维哈尔",
//                "哈格兰",
//                "耐里斯特",
//                "尤索克",
//                "淡水鳄",
//                "海鳄",
//                "大副斯涅利格",
//                "哈林多尔船长",
//                "黑铁叛军",
//                "坑道鼠歹徒",
//                "坑道鼠地卜师",
//                "坑道鼠征粮官",
//                "坑道鼠勘探员",
//                "安东修士",
//                "老黑熊",
//                "灰斑黑熊",
//                "黑熊首领",
//                "山鹫",
//                "冰爪熊",
//                "格劳姆格",
//                "纳什尔",
//                "布劳勒尔",
//                "卓克苏尔",
//                "麻疯侏儒",
//                "主教法席恩",
//                "炼金师玛洛瑞",
//                "草药师博米洛伊",
//                "奥尔苏迪",
//                "格瑞夫",
//                "旅店老板贝尔姆",
//                "军需官哈德森",
//                "伽文神父",
//                "勘察员吉恩",
//                "矿场主管瑟斯丁",
//                "高布勒尔",
//                "霜鬃长老阿克提卡斯",
//                "冰须",
//                "大主教本尼迪塔斯",
//                "卡苏斯修士",
//                "长毛兔",
//                "萨尔图斯",
//                "学徒索林",
//                "厨师格瑞姆",
//                "亚当",
//                "比利",
//                "贾斯廷",
//                "布兰顿",
//                "罗曼",
//                "米兰",
//                "赛恩",
//                "克拉克",
//                "玛杜克",
//                "斯纳尔",
//                "布劳恩",
//                "罗格瓦尔",
//                "塞斯塔",
//                "瓦加什",
//                "奥比斯雷",
//                "霜鬃先知",
//                "大头目加尔高什",
//                "克拉格",
//                "斯兰达",
//                "松鼠",
//                "苏姗妮",
//                "菲尔",
//                "蟾蜍",
//                "默尔下士",
//                "塞斯曼下士",
//                "格瑞兹拉克",
//                "黑爪加尔德斯",
//                "赫格拉姆",
//                "费泽鲁尔",
//                "克里斯托弗修士",
//                "巫医安巴格瓦",
//                "布兰玛尔",
//                "旅店老板赫布瑞克",
//                "格雷塔",
//                "加克",
//                "卡利",
//                "赞吉尔僵尸",
//                "赞吉尔巫医",
//                "赞吉尔纳迦",
//                "高拉什",
//                "摩卡什",
//                "执政官塞弗伦",
//                "血色信徒",
//                "夜行蝙蝠",
//                "癞皮夜行蝙蝠",
//                "执行官塞加德",
//                "康达",
//                "药剂师乔汉",
//                "暗眼骷髅法师",
//                "血色传教士",
//                "血色苦行修士",
//                "血色低阶牧师",
//                "血色前锋",
//                "巨型夜行蝙蝠",
//                "吸血夜行蝙蝠",
//                "银背雌猩猩",
//                "穆克拉",
//                "血帆法师",
//                "血帆流氓",
//                "血帆术士",
//                "血帆水手",
//                "管理员摩尔多",
//                "暗影牧师萨维斯",
//                "执行官阿伦",
//                "北郡守卫",
//                "军需官希克斯",
//                "血帆大法师",
//                "达高尔队长",
//                "血色保镖",
//                "派瑞恩队长",
//                "瓦松队长",
//                "麦拉其队长",
//                "芬布斯",
//                "埃伦",
//                "洛克鳄",
//                "瑞恩多尔",
//                "布隆克",
//                "哈姆霍克",
//                "典狱官塞尔沃特",
//                "兹吉",
//                "杰塔瑞斯将军",
//                "蛆眼",
//                "基尔尼格",
//                "腐皮秘法师",
//                "祖达尔萨",
//                "骷髅巫师",
//                "恐惧骸骨",
//                "骷髅刽子手",
//                "骷髅军官",
//                "骷髅侍僧",
//                "巨型灰斑熊",
//                "食腐秃鹫",
//                "血色法师",
//                "血色占星师",
//                "血色骑士",
//                "血色圣骑士",
//                "血色法官",
//                "血色高阶牧师",
//                "玛达萨尔",
//                "普特迪乌斯",
//                "高阶牧师赛尔邓尼斯",
//                "魅魔",
//                "鸦爪奴隶",
//                "达拉然学徒",
//                "鸦爪仆从",
//                "鸦爪勇士",
//                "鸦爪之手",
//                "达拉然卫士",
//                "达拉然巫师",
//                "断骨骷髅",
//                "焚木村守卫",
//                "月怒守卫",
//                "穆亚德",
//                "达拉然守卫",
//                "达拉然法师",
//                "达拉然咒术师",
//                "达拉然书记员",
//                "血色十字军俘虏",
//                "绵羊",
//                "提瑞斯法雇农",
//                "药剂师伦弗利尔",
//                "腐皮盗墓贼",
//                "高级执行官哈德瑞克",
//                "癞爪",
//                "奈塔拉什",
//                "小劣魔",
//                "劣魔",
//                "塔琳德拉",
//                "绿爪",
//                "巨翼枭",
//                "巨翼恶枭",
//                "巨翼猎枭",
//                "恶灵劣魔",
//                "影魂劣魔",
//                "暗魂劣魔",
//                "瘤背园丁",
//                "瘤背萨满祭司",
//                "瘤背占卜师",
//                "血羽女巫",
//                "血羽风巫",
//                "血羽女族长",
//                "林精",
//                "林精泥泞兽",
//                "林精长老",
//                "迈雷纳斯",
//                "大槌乌萨尔",
//                "守护古树",
//                "弃灵",
//                "大药剂师法拉尼尔",
//                "胡达尔",
//                "管理员伊尔萨莱恩",
//                "德纳兰",
//                "纳克罗什酋长",
//                "山羊",
//                "斯托菲队长",
//                "药剂师博拉尔德",
//                "黑老鼠",
//                "塞达",
//                "法鲁萨",
//                "铁匠兰德",
//                "大法师阿塔瑞克",
//                "暗影牧师奥利斯特",
//                "黑暗牧师杜斯滕",
//                "伊莎贝拉",
//                "黑暗牧师贝里尔",
//                "石巨兽",
//                "砂石地占师",
//                "阿高尔",
//                "蓟熊",
//                "狂暴蓟熊",
//                "灰斑蓟熊",
//                "奥肯斯古尔",
//                "黑木萨满祭司",
//                "影爪",
//                "卡尼沃斯",
//                "恶灵劣魔",
//                "野生劣魔",
//                "利斯林",
//                "公告员古德曼",
//                "灰雾先知",
//                "戴瑟雷萨特",
//                "高级执行官达萨利亚",
//                "药剂师林度恩",
//                "沙琳德拉",
//                "克鲁斯克",
//                "乌比",
//                "托格萨",
//                "德鲁尔",
//                "破碎岭法师",
//                "玛格索尔",
//                "治安官雷德帕斯",
//                "希尔斯布莱德裁缝",
//                "希尔斯布莱德农民",
//                "达拉然持盾守卫",
//                "达拉然法师",
//                "斯坦利",
//                "梅里萨拉",
//                "伊萨拉斯",
//                "管理员凯斯",
//                "高迪尔",
//                "艾丽萨",
//                "暗影大法师",
//                "纳伽兹",
//                "仆从瓦里克",
//                "事件生成器001",
//                "波恩塞德镇长",
//                "暗滩唤魔师",
//                "暮光信徒",
//                "暮光暴徒",
//                "丹加洛克火枪手",
//                "丹加洛克牧师",
//                "野生狮鹫兽",
//                "灰熊",
//                "旅店老板安德森",
//                "老灰熊",
//                "达拉然召唤师",
//                "希尔斯布莱德雇农",
//                "学徒哈尼维尔",
//                "野生山地狮",
//                "希尔斯布莱德议员",
//                "旅店老板沙恩",
//                "扎瑞斯",
//                "铁匠维林坦",
//                "瑞克特尔",
//                "奥丽娜",
//                "克甘达玛",
//                "典狱官贝拉摩尔",
//                "守财奴格雷尔伯格",
//                "塔尔格",
//                "玛克拉克",
//                "戈洛姆斯",
//                "瓦里玛萨斯",
//                "狱卒埃斯顿",
//                "狱卒玛尔根",
//                "学徒塞万德",
//                "厨师杰森",
//                "看守员博胡恩",
//                "萨缪尔森少校",
//                "乳牛",
//                "纳瑞尔拉萨斯",
//                "平民维尔克斯",
//                "食腐虫",
//                "指挥官阿格罗戈西",
//                "先知摩克萨尔丁",
//                "格拉尼斯塔德"
//        };
//        String[] b = new String[]{
//                "Worn Shortsword",
//                "Bent Staff",
//                "Worn Mace",
//                "Worn Axe",
//                "Apprentice's Boots",
//                "Apprentice's Robe",
//                "Acolyte's Robe",
//                "Acolyte's Shoes",
//                "Layered Tunic",
//                "Dwarven Leather Pants",
//                "Dwarven Cloth Britches",
//                "Soft Fur-lined Shoes",
//                "Dirty Leather Vest",
//                "Tough Jerky",
//                "Minor Healing Potion",
//                "Thug Pants",
//                "Thug Boots",
//                "Trapper's Shirt",
//                "Deprecated Tauren Trapper's Pants",
//                "Rugged Trapper's Boots",
//                "Brawler's Pants",
//                "Brawler's Boots",
//                "Rugged Trapper's Pants",
//                "Rugged Trapper's Shirt",
//                "Primitive Kilt",
//                "Primitive Mantle",
//                "Refreshing Spring Water",
//                "Garrick's Head",
//                "Scalemail Vest",
//                "Scalemail Pants",
//                "Scalemail Boots",
//                "Dalaran Sharp",
//                "Dwarven Mild",
//                "Dull Frenzy Scale",
//                "Rough Vulture Feathers",
//                "Buzzard Beak",
//                "Destiny",
//                "Bracers of the People's Militia",
//                "Tattered Cloth Gloves",
//                "Dirty Leather Gloves",
//                "Scalemail Gloves",
//                "Rabbit Handler Gloves",
//                "Brawler Gloves",
//                "Goretusk Liver",
//                "Goretusk Liver Pie",
//                "Gnoll Paw",
//                "Notched Shortsword",
//                "Recipe: Westfall Stew",
//                "Stringy Vulture Meat",
//                "Murloc Eye",
//                "Goretusk Snout",
//                "Okra",
//                "Westfall Stew",
//                "Rolf and Malakai's Medallions",
//                "Holy Spring Water",
//                "Sack of Barley",
//                "Sack of Corn",
//                "Sack of Rye",
//                "A Sycamore Branch",
//                "Bundle of Charred Oak",
//                "Thunderbrew's Boot Flask",
//                "Marshal McBride's Documents",
//                "Stormwind Armor Marker",
//                "Tough Wolf Meat",
//                "Red Burlap Bandana",
//                "Dragonmaw Shortsword",
//                "Shortsword of Vengeance",
//                "Melted Candle",
//                "Tunnel Pick",
//                "Ice-covered Bracers",
//                "Silverleaf",
//                "Flanged Mace",
//                "Long Bo Staff",
//                "Lumberjack Axe",
//                "Chunk of Boar Meat",
//                "Pointy Crocolisk Tooth",
//                "Chipped Boar Tusk",
//                "Large Candle",
//                "Gold Dust",
//                "Malachite",
//                "Vendetta",
//                "Prowler Teeth",
//                "Kobold Excavation Pick",
//                "Shiny Seashell",
//                "Torn Murloc Fin",
//                "Stone Gnoll Hammer",
//                "Painted Gnoll Armband",
//                "Light Hide",
//                "Mageroyal",
//                "Slitherskin Mackerel",
//                "Stout Battlehammer",
//                "Forester's Axe",
//                "Gnarled Ash Staff",
//                "Knitted Sandals",
//                "Knitted Gloves",
//                "Knitted Pants",
//                "Knitted Tunic",
//                "Rough Leather Boots",
//                "Rough Leather Gloves",
//                "Rough Leather Pants",
//                "Rough Leather Vest",
//                "Large Blue Sack",
//                "Small Red Pouch",
//                "Bloodrazor",
//                "Hammer of the Northern Wind",
//                "Axe of the Deep Woods",
//                "Glowing Brightwood Staff",
//                "Flask of Oil",
//                "Small Hand Blade",
//                "Tigerseye",
//                "Slicer Blade",
//                "Riverpaw Leather Vest",
//                "Brutish Riverpaw Axe",
//                "Wicked Blackjack",
//                "Small Blue Pouch",
//                "Red Leather Bandana",
//                "Silver Defias Belt",
//                "Lifestone",
//                "Large Rope Net",
//                "Heavy Weave Armor",
//                "Heavy Weave Pants",
//                "Heavy Weave Gloves",
//                "Heavy Weave Shoes",
//                "Furlbrow's Pocket Watch",
//                "Tanned Leather Boots",
//                "Tanned Leather Gloves",
//                "Tanned Leather Pants",
//                "Tanned Leather Jerkin",
//                "Cutlass",
//                "Mace",
//                "Hatchet",
//                "Quarter Staff",
//                "Blue Leather Bag",
//                "Large Red Sack",
//                "Lesser Healing Potion",
//                "Fine Cloth Shirt",
//                "Cavalier's Boots",
//                "Runed Ring",
//                "Gloom Reaper",
//                "Knightly Longsword",
//                "Leaden Mace",
//                "Monk's Staff",
//                "Gloves of Holy Might",
//                "Ardent Custodian",
//                "Dazzling Longsword",
//                "Fiery War Axe",
//                "Flurry Axe",
//                "Rockslicer",
//                "Staff of Jordan",
//                "Fist-sized Spinneret",
//                "Staff of Horrors",
//                "Ghoul Rib",
//                "Black Metal Axe",
//                "Black Metal Shortsword",
//                "Pound of Flesh",
//                "Naga Battle Gloves",
//                "A Dusty Unsent Letter",
//                "Twisted Chanter's Staff",
//                "Gnoll Casting Gloves",
//                "Dire Wolf Fang",
//                "Madwolf Bracers",
//                "Venom Web Fang",
//                "An Undelivered Letter",
//                "Ironwood Treebranch",
//                "Large Ogre Chain Armor",
//                "Red Silk Bandana",
//                "A Torn Journal Page",
//                "Deviate Hide Pack",
//                "Wicked Spiked Mace",
//                "A Faded Journal Page",
//                "Dacian Falx",
//                "Longsword",
//                "Maul",
//                "Flail",
//                "Battle Axe",
//                "Double Axe",
//                "Long Staff",
//                "Healing Potion",
//                "Fel Steed Saddlebags",
//                "Large Rucksack",
//                "Stalvan's Reaper",
//                "Night Watch Shortsword",
//                "Midnight Mace",
//                "Black Duskwood Staff",
//                "Muddy Journal Pages",
//                "A Bloodstained Journal Page",
//                "Robes of Insight",
//                "Freezing Band",
//                "Warden Staff",
//                "Elemental Mage Staff",
//                "Scroll of Strength",
//                "Scroll of Intellect",
//                "William's Shipment",
//                "Healing Herb",
//                "Pork Belly Pie",
//                "Bernice's Necklace",
//                "Red Linen Sash",
//                "Fire Sword of Crippling",
//                "Brass Collar",
//                "Well-used Sword",
//                "Compact Hammer",
//                "Gnarled Short Staff",
//                "Sharp Axe",
//                "Iron Rivet",
//                "Lean Wolf Flank",
//                "Seasoned Wolf Kabob",
//                "Red Linen Bandana",
//                "Plate Helmet D2 (test)",
//                "Mail Helmet A (Test)",
//                "Hard Spider Leg Tip",
//                "Shadowhide Pendant",
//                "Defias Renegade Ring",
//                "Defias Mage Ring",
//                "Tough Condor Meat",
//                "Crisp Spider Meat",
//                "Redridge Goulash",
//                "Glyph of Azora",
//                "Conjured Bread",
//                "Conjured Rye",
//                "Ring of Pure Silver",
//                "Feet of the Lynx",
//                "Flash Bundle",
//                "Ghoul Fang",
//                "Vial of Spider Venom",
//                "Totem of Infliction",
//                "Horn of the Timber Wolf",
//                "Belt of the People's Militia",
//                "Rod of the Sleepwalker",
//                "Lavishly Jeweled Ring",
//                "Solid Metal Club",
//                "Militia Quarterstaff",
//                "Militia Shortsword",
//                "Dented Buckler",
//                "Small Targe",
//                "Skullflame Shield",
//                "Blackskull Shield",
//                "Well-stitched Robe",
//                "Grayson's Torch",
//                "Weather-worn Boots",
//                "A Gold Tooth",
//                "Oil of Olaf",
//                "Explosive Rocket",
//                "Ice Cold Milk",
//                "Scroll of Stamina",
//                "Scroll of Spirit",
//                "Brass-studded Bracers",
//                "Elastic Wristguards",
//                "Spiked Collar",
//                "Overseer's Ring",
//                "Overseer's Cloak",
//                "Bag of Marbles",
//                "Banded Buckler",
//                "Bastard Sword",
//                "Kobold Mining Shovel",
//                "Tabar",
//                "Giant Mace",
//                "Claymore",
//                "Large Wooden Shield",
//                "Dull Heater Shield",
//                "Wall Shield",
//                "Aegis of Stormwind",
//                "The Green Tower",
//                "Melon Juice",
//                "Moss Agate",
//                "Murphstar",
//                "Maybell's Love Letter",
//                "Shadowgem",
//                "Gnoll War Harness",
//                "Gnoll Spittle",
//                "Gnoll Kindred Bracers",
//                "Gnoll Punisher",
//                "Support Girdle",
//                "Unknown Reward",
//                "Heavy Gnoll War Club",
//                "Redridge Machete",
//                "Lupine Axe",
//                "Underbelly Whelp Scale",
//                "Linen Bandage",
//                "Gramma Stonefield's Note",
//                "Lesser Firestone",
//                "Crystal Kelp Frond",
//                "Invisibility Liquor",
//                "Tharil'zun's Head",
//                "Midnight Orb",
//                "Keg of Thunderbrew Lager",
//                "Brain Hacker",
//                "Headbasher",
//                "Scorpion Sting",
//                "Finely Woven Cloak",
//                "Forest Chain",
//                "Hops",
//                "Deputy Chain Coat",
//                "Fire Hardened Buckler",
//                "Cloaked Hood",
//                "Sparkmetal Coif",
//                "Verner's Note",
//                "Crate of Horseshoes",
//                "Giant Tarantula Fang",
//                "Large Venom Sac",
//                "Butcher's Cleaver",
//                "The State of Lakeshire",
//                "The General's Response",
//                "Blackrock Mace",
//                "Robes of the Shadowcaster",
//                "Lesser Belt of the Spire",
//                "Lesser Staff of the Spire",
//                "Black Whelp Gloves",
//                "Bridgeworker's Gloves",
//                "Riding Gloves",
//                "Wolfmane Wristguards",
//                "Gold Pickup Schedule",
//                "Oslow's Toolbox",
//                "Smith's Trousers",
//                "Ghoul Fingers",
//                "Lei of Lilies",
//                "Hardened Root Staff",
//                "Night Reaver",
//                "Ring of Iron Will",
//                "Fishliver Oil",
//                "Daffodil Bouquet",
//                "Sauteed Sunfish",
//                "Wiley's Note",
//                "Abercrombie's Crate",
//                "Fingerbone Bracers",
//                "Shaw's Report",
//                "Buckskin Cape",
//                "Captain Sander's Treasure Map",
//                "A Clue to Sander's Treasure",
//                "Lion-stamped Gloves",
//                "Stormwind Chain Gloves",
//                "Another Clue to Sander's Treasure",
//                "Final Clue to Sander's Treasure",
//                "Ragged Leather Vest",
//                "Ragged Leather Pants",
//                "Ragged Leather Boots",
//                "Ragged Leather Gloves",
//                "Ragged Leather Belt",
//                "Ragged Leather Bracers",
//                "Ragged Cloak",
//                "Frayed Shoes",
//                "Frayed Cloak",
//                "Frayed Gloves",
//                "Frayed Pants",
//                "Frayed Robe",
//                "A Mysterious Message",
//                "Rock Mace",
//                "Stone Tomahawk",
//                "Dull Blade",
//                "Thistlewood Axe",
//                "Ghoulfang",
//                "Crooked Staff",
//                "Kobold Mining Mallet",
//                "Riverpaw Mystic Staff",
//                "Driftwood Club",
//                "Apprentice's Pants",
//                "Acolyte's Pants",
//                "Magic Candle",
//                "Green Tea Leaf",
//                "Tidal Charm",
//                "Foamspittle Staff",
//                "Pearl-encrusted Spear",
//                "Solomon's Plea to Westfall",
//                "Stoutmantle's Response to Solomon",
//                "Solomon's Plea to Darkshire",
//                "Ebonlocke's Response to Solomon",
//                "Withered Staff",
//                "Crude Bastard Sword",
//                "Feeble Sword",
//                "Cracked Sledge",
//                "Carpenter's Mallet",
//                "Rusty Hatchet",
//                "Beaten Battle Axe",
//                "Worn Leather Belt",
//                "Worn Leather Boots",
//                "Worn Leather Bracers",
//                "Worn Hide Cloak",
//                "Worn Leather Gloves",
//                "Worn Leather Pants",
//                "Worn Leather Vest",
//                "Patchwork Shoes",
//                "Patchwork Cloak",
//                "Patchwork Gloves",
//                "Patchwork Pants",
//                "Patchwork Armor",
//                "Glowing Wax Stick",
//                "Frontier Britches",
//                "Warrior's Shield",
//                "Gnoll Skull Basher",
//                "Jeweled Amulet of Cainwyn",
//                "Blackrock Pauldrons",
//                "Blackrock Boots",
//                "Ring of Saviors",
//                "Blackrock Gauntlets",
//                "Minor Channeling Ring",
//                "Bottle of Zombie Juice",
//                "Spectral Comb",
//                "Axe of the Enforcer",
//                "Blackrock Champion's Axe",
//                "Shadowhide Mace",
//                "Shadowhide Maul",
//                "Shadowhide Scalper",
//                "Shadowhide Two-handed Sword",
//                "Slayer's Battle Axe",
//                "Ring of the Shadow",
//                "Buzzard Talon",
//                "Tigerbane",
//                "Spotted Sunfish",
//                "Murloc Fin",
//                "Scimitar of Atun",
//                "Murloc Skin Bag",
//                "Riverside Staff",
//                "Small Venom Sac",
//                "Snapped Spider Limb",
//                "Scroll of Agility II",
//                "Scroll of Protection II",
//                "Salma's Oven Mitts",
//                "Fist of the People's Militia",
//                "Grimclaw",
//                "Shadowfang",
//                "Face Smasher",
//                "Witching Stave",
//                "Pitchfork",
//                "Tree Bark Jacket",
//                "Conjured Pumpernickel",
//                "Avenger's Armor",
//                "Gloomshroud Armor",
//                "Guardian Talisman",
//                "Ring of Precision",
//                "Heavy Marauder Scimitar"
//        };
//        for (int i = 1; i < 301; i++) {
//            UserEntity user = new UserEntity();
//            user.setAvatar("http://www.spoom.com/avatar/user_" + i + ".png");
//            user.setUsername("user_" + (100000 + i));
//            user.setCreateTime(new Date());
//            user.setEnabled(true);
//            user.setPassword(DigestUtils.sha256Hex("000000"));
//            Random random = new Random();
//            long j = random.nextInt(999999999);
//            user.setTelephone("18" + j);
//            user.setGender(random.nextInt(2));
//            user.setEmail(j + "@qq.com");
//            user.setRegion("浙江 杭州");
//            user.setMotto(b[i]);
//            user.setNickname(a[i]);
//            user.setOnline(false);
//            user.setLastLoginTime(new Date());
//            logger.debug("user: " + user.getNickname());
//            try {
//                userService.insert(user);
//                logger.debug("insert user success, user name: " + user.getNickname());
//            } catch (Exception e) {
//                logger.error("insert user error, user name: " + user.getNickname());
//            }
//        }
//    }
//
//    @Test
//    public void testInsertFriend() {
//        Random random = new Random();
//        for (int i = 1; i < 301; i++) {
//            for (int j = 1; j < 301; j++) {
//                boolean isFriend = random.nextBoolean();
//                if (isFriend && i != j) {
//                    try {
//                        userMapper.addFriend(
//                                (long) i,
//                                (long) j,
//                                random.nextInt(2),
//                                random.nextInt(2),
//                                random.nextInt(2),
//                                random.nextInt(2),
//                                random.nextInt(2));
//                        userMapper.addFriend(
//                                (long) j,
//                                (long) i,
//                                random.nextInt(2),
//                                random.nextInt(2),
//                                random.nextInt(2),
//                                random.nextInt(2),
//                                random.nextInt(2));
//                    } catch (Exception ignored) {
//
//                    }
//                }
//            }
//        }
//    }
}
